/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Ascendant: typeof import('./src/components/Ascendant.vue')['default']
    AstrologicalChart: typeof import('./src/components/AstrologicalChart.vue')['default']
    AstrologicalHouseChart: typeof import('./src/components/AstrologicalHouseChart.vue')['default']
    BirthdatePassword: typeof import('./src/components/BirthdatePassword.vue')['default']
    BirthdayBook: typeof import('./src/components/BirthdayBook.vue')['default']
    BirthdayFlower: typeof import('./src/components/BirthdayFlower.vue')['default']
    Cancel: typeof import('./src/components/ChatComponent/Cancel.vue')['default']
    CheatingPerson: typeof import('./src/components/CheatingPerson.vue')['default']
    ChineseZodiacFortune: typeof import('./src/components/ChineseZodiacFortune.vue')['default']
    Chouqiansuanming: typeof import('./src/components/Chouqiansuanming.vue')['default']
    ConsteBloodPersonality: typeof import('./src/components/ConsteBloodPersonality.vue')['default']
    ConstellationInquir: typeof import('./src/components/ConstellationInquir.vue')['default']
    ConstellationRankingItem: typeof import('./src/components/common/ConstellationRankingItem.vue')['default']
    ConstellationRankingList: typeof import('./src/components/ConstellationRankingList.vue')['default']
    Constellations48: typeof import('./src/components/Constellations48.vue')['default']
    DateTimeSelect: typeof import('./src/components/ChatComponent/DateTimeSelect.vue')['default']
    DescendingZodiac: typeof import('./src/components/DescendingZodiac.vue')['default']
    DisLikeReason: typeof import('./src/components/ChatComponent/DisLikeReason.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Header: typeof import('./src/components/Header.vue')['default']
    Horoscope: typeof import('./src/components/Horoscope.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MoonSign: typeof import('./src/components/MoonSign.vue')['default']
    MoreShareMb: typeof import('./src/components/ChatComponent/moreShareMb.vue')['default']
    PlanetInHouse: typeof import('./src/components/PlanetInHouse.vue')['default']
    PlanetInSign: typeof import('./src/components/PlanetInSign.vue')['default']
    RelatedQuestions: typeof import('./src/components/ChatComponent/RelatedQuestions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectModelDialog: typeof import('./src/components/ChatComponent/selectModelDialog.vue')['default']
    SubscribeType: typeof import('./src/components/ChatComponent/SubscribeType.vue')['default']
    Success: typeof import('./src/components/ChatComponent/Success.vue')['default']
    TextComponents: typeof import('./src/components/ChatComponent/TextComponents.vue')['default']
    TypeTab: typeof import('./src/components/TypeTab.vue')['default']
    ZodiacQuery: typeof import('./src/components/ZodiacQuery.vue')['default']
  }
}
